package com.dnunezv.u4_actividad3_creacion_app.repository.origenes

import com.dnunezv.u4_actividad3_creacion_app.domain.origenes.FuenteLiderComunitario
import com.dnunezv.u4_actividad3_creacion_app.domain.origenes.FuenteLiderComunitarioId
import org.springframework.data.jpa.repository.JpaRepository

interface FuenteLiderComunitarioRepository : JpaRepository<FuenteLiderComunitario, FuenteLiderComunitarioId>
